apiVersion: v1
kind: Namespace
metadata:
  name: service-lab
  labels:
    istio-injection: enabled
    security-lab: protected
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.36
